name: Deploy Contract
on:
  pull_request:
    branches:
      - main

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - name: check go version
        run: |
          go version
          sudo env "PATH=$PATH" go version
          go env
          sudo env "PATH=$PATH" go env
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          go version
          sudo -E go version
          npm install
          go version
          sudo -E go version
          go env
          sudo -E go env
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test contract
        run: |
          go version
          sudo -E go version
          go env
          sudo -E go env
          sudo -E make contract-tools
      - name: Test contract2
        run: |
          go version
          sudo -E go version
          go env
          sudo -E go env
          sudo -E make test-solidity
        if: env.GIT_DIFF
